services:
  - type: web
    name: blackcore-pegasus
    env: node
    repo: https://github.com/cherryv1/BlackCore-Pegasus.git
    branch: main
    plan: free
    healthCheckPath: /
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: "${PORT}"
      - key: NODE_ENV
        value: "production"
